### PR TITLE
Optimize the gcp_logging_log_entry table result or result timing by applying a timestamp filter and added the columns json_payload, proto_payload, metadata, resource, operation and tags Closes #507

### LINKED ISSUE #507: Optimize the gcp_logging_log_entry table result or result timing by applying a timestamp filter
**Describe the bug**
The timestamp qual is ignored, so it's pulling down all data at once (the docs say it should work)

**Steampipe version (`steampipe -v`)**
Example: Steampipe v0.21.1

**Plugin version (`steampipe plugin list`)**
Example: v0.45.0

**To reproduce**
Run the following query:
```
select log_name, receive_timestamp,timestamp, resource_type from gcp_logging_log_entry where log_name = 'projects/hsrket-aaa/logs/diagnostic-log' and timestamp <= '2023-09-29T10:09:08+05:30';
```
It should only fetch the results whose log entry timestamp value is less than equal to the provided timestamp instead of fetching all the results and filtering them in the steampipe level.

**Expected behavior**
The table should take less time if we apply any filter for the timestamp.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
N/A
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select log_name, receive_timestamp,timestamp, resource_type from gcp_logging_log_entry where log_name = 'projects/isldke-aaa/logs/diagnostic-log' and timestamp = '2023-09-29T10:09:08+05:30'
+----------+-------------------+-----------+---------------+
| log_name | receive_timestamp | timestamp | resource_type |
+----------+-------------------+-----------+---------------+
+----------+-------------------+-----------+---------------+

> select log_name, receive_timestamp,timestamp, resource_type from gcp_logging_log_entry where log_name = 'projects/isldke-aaa/logs/diagnostic-log' and timestamp <= '2023-09-29T10:09:08+05:30'
+-----------------------------------------+---------------------------+---------------------------+---------------+
| log_name                                | receive_timestamp         | timestamp                 | resource_type |
+-----------------------------------------+---------------------------+---------------------------+---------------+
| projects/isldke-aaa/logs/diagnostic-log | 2023-09-29T09:45:09+05:30 | 2023-09-29T09:45:06+05:30 | k8s_container |
| projects/isldke-aaa/logs/diagnostic-log | 2023-09-29T09:45:12+05:30 | 2023-09-29T09:45:09+05:30 | k8s_container |
+-----------------------------------------+---------------------------+---------------------------+---------------+

Time: 63.4s. Rows fetched: 2. Hydrate calls: 0.

> select log_name, receive_timestamp,timestamp, resource_type from gcp_logging_log_entry where log_name = 'projects/isldke-aaa/logs/diagnostic-log' and timestamp >= '2023-09-29T10:09:08+05:30'
+-----------------------------------------+---------------------------+---------------------------+---------------+
| log_name                                | receive_timestamp         | timestamp                 | resource_type |
+-----------------------------------------+---------------------------+---------------------------+---------------+
| projects/isldke-aaa/logs/diagnostic-log | 2023-09-29T10:09:18+05:30 | 2023-09-29T10:09:16+05:30 | k8s_container |
| projects/isldke-aaa/logs/diagnostic-log | 2023-09-29T10:09:11+05:30 | 2023-09-29T10:09:08+05:30 | k8s_container |
+-----------------------------------------+---------------------------+---------------------------+---------------+

Time: 5.8s. Rows fetched: 2. Hydrate calls: 0.
```
</details>

### CODE REVIEW

File: gcp/table_gcp_logging_log_entry.go [hunk 1]
```diff
@@ -186,8 +217,9 @@ func listGcpLoggingLogEntries(ctx context.Context, d *plugin.QueryData, h *plugi
 	}
 
 	// Max limit isn't mentioned in the documentation
-	// Default limit is set as 1000
-	pageSize := types.Int64(1000)
+	// Default limit is set as 10000
+	// After conducting tests with maximum page sizes of 1000, 5000, 17000, 20000, and 30000, we decided to stick with a page size of 10000 for performance improvement.
```
Comment (cbruno10) [inline gcp/table_gcp_logging_log_entry.go:221]:
```suggestion
	// 10000 seems to be a balanced limit, based on initial tests for retrieving 140k log entries: 5000 (124s), 10000 (88s), 20000 (84s)
```

**Review by cbruno10 — CHANGES_REQUESTED** [review]
Other suggestions:
- Remove "log_entry_" prefix from columns.
- Consolidate JSON columns so each property has only 1 column, we can always add more columns later on. This will be a breaking change but I think will make the table columns more consistent and easy to maintain in the future.

File: gcp/table_gcp_logging_log_entry.go [hunk 2]
```diff
@@ -120,34 +103,47 @@ func tableGcpLoggingLogEntry(_ context.Context) *plugin.Table {
...
 				Type:        proto.ColumnType_JSON,
 			},
+			{
+				Name:        "metadata",
+				Description: "Auxiliary metadata for a MonitoredResource object. MonitoredResource objects contain the minimum set of information to uniquely identify a monitored resource instance.",
+				Type:        proto.ColumnType_JSON,
+			},
+			{
+				Name:        "labels",
+				Description: "A map of key, value pairs that provides additional information about the log entry. The labels can be user-defined or system-defined.User-defined labels are arbitrary key, value pairs that you can use to classify logs.System-defined labels are defined by GCP services for platform logs.",
```
Comment (cbruno10) [inline gcp/table_gcp_logging_log_entry.go:144]: Please add missing spaces

File: gcp/table_gcp_logging_log_entry.go [hunk 3]
```diff
@@ -120,34 +103,47 @@ func tableGcpLoggingLogEntry(_ context.Context) *plugin.Table {
...
 				Description: "Source code location information associated with the log entry, if any.",
 				Type:        proto.ColumnType_JSON,
 			},
+			{
+				Name:        "metadata",
+				Description: "Auxiliary metadata for a MonitoredResource object. MonitoredResource objects contain the minimum set of information to uniquely identify a monitored resource instance.",
+				Type:        proto.ColumnType_JSON,
+			},
+			{
+				Name:        "labels",
```
Comment (cbruno10) [inline gcp/table_gcp_logging_log_entry.go:143]: Please add `tags` column as well

**Review by cbruno10 — APPROVED** [review]
