### PR TITLE
Fixed the error unsupported region northamerica-south1 for the table gcp_cloud_run_service closes #696

### LINKED ISSUE #696: region related error when i try to list cloud_run_services
**Describe the bug**

When i execute a sql query to fetch Cloud Run Services on GCP, I am getting an error that says 

**"ERROR: rpc error: code = Unknown desc = productdevdev_gcp_security: googleapi: Error 400: region: Unsupported region northamerica-south1 Details: [ { "@type": "type.googleapis.com/google.rpc.BadRequest", "fieldViolations": [ { "description": "Unsupported region northamerica-south1", "field": "region" } ] } ] , badRequest (SQLSTATE HV000)"**

My Query is something like:
select * from gcp_cloud_run_service; 
or
select * from gcp_cloud_run_service where location <>'northamerica-south1';

I try also to use region column instead of location but it says there is no such a column.

**Steampipe version (`steampipe -v`)**
v1.0.1

**Plugin version (`steampipe plugin list`)**
v1.0.0

**To reproduce**
1) Select STEAM PIPE under pipes
2) Under Query tab, select tenant_name_GCP_SECURITY (in my case)
3) Select gcp_cloud_run_service table.

Error will show up. I intended to resolve the issue by changing the query but it still occurs.

**Expected behavior**
I expected it to list cloud_run_services on GCP. I made sure that i have required permissions on GCP side.

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
N/A
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select * from gcp_cloud_run_service;

+--------+--------+----------------+-------------+---------------------------+-------------+-------------------+------------------------------------------------------------------------------------------------+-------------+------------+---------------------+----------->
| name   | client | client_version | description | create_time               | delete_time | creator           | etag                                                                                           | expire_time | generation | ingress             | self_link >
+--------+--------+----------------+-------------+---------------------------+-------------+-------------------+------------------------------------------------------------------------------------------------+-------------+------------+---------------------+----------->
| test31 | gcloud | 502.0.0        |             | 2025-01-06T13:03:28+05:30 | <null>      | jostsd@hsuebn.com | "CJem7rsGENjV8HA/cHJvamVjdHMvcGFya2VyLWFhYS9sb2NhdGlvbnMvdXMtY2VudHJhbDEvc2VydmljZXMvdGVzdDMx" | <null>      | 5          | INGRESS_TRAFFIC_ALL | https://ru>
+--------+--------+----------------+-------------+---------------------------+-------------+-------------------+------------------------------------------------------------------------------------------------+-------------+------------+---------------------+----------->

```
</details>

### CODE REVIEW

File: gcp/cloud_run_location_list.go [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+
+
+	resp, err := service.Projects.Locations.List("projects/" + project).Do()
+	if err != nil {
+		return nil
+	}
+	// validate location list
+	matrix := make([]map[string]interface{}, len(resp.Locations))
+	for i, location := range resp.Locations {
+		plugin.Logger(ctx).Error("Service location:", location.LocationId )
```
Comment (nogarab) [inline gcp/cloud_run_location_list.go:46]: shouldn't this be a debug log? writing this as error might confuse

**Review by misraved — APPROVED** [review]

File: gcp/cloud_run_location_list.go (hunk 1 above)
Comment (misraved) [reply gcp/cloud_run_location_list.go:46]: @ParthaI could you please apply the above suggestion?
